[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
test = "python -m pytest --verbose --cov=wakatools --cov-report xml --cov-report term"
test-local = "pytest -v --cov"
format = "black ."
lint = "ruff check --fix ./src/wakatools"
build-docs = "sphinx-build -b html docs ./docs/build"
measure-complexity = "radon cc ./src/wakatools -s"
rm-jupyter = "rm -r ./docs/jupyter_execute"
rm-build = "rm -r ./docs/build"
rm-generated = "rm -r ./docs/api_reference/generated"
rebuild-docs = { depends-on = ["rm-jupyter", "rm-build", "rm-generated", "build-docs"] }

[dependencies]
python = ">=3.12"
pip = "*"
numpy = "*"
scipy = "*"
pandas = "*"
geopandas = "*"
rioxarray = "*"
xarray = "*"
shapely = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
myst-parser = "*"
pydata-sphinx-theme = "*"
sphinx-design = "*"
myst-nb = "*"
pre-commit = "*"
radon = "*"

[pypi-dependencies]
wakatools = { path = ".", editable = true }
geost = "*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[environments]
default = { features = ["py314"], solve-group = "py314" }
py313 = { features = ["py313"], solve-group = "py313" }
py314 = { features = ["py314"], solve-group = "py314" }
