name: Wakatools CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install ruff
        run: pip install ruff
      - name: Run linter
        run: ruff check ./src/wakatools

  test:
    name: ${{ matrix.pixi-environment }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        pixi-environment:
          - py312
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          manifest-path: pyproject.toml
      - name: Run tests in current test environment
        run: pixi run -e ${{ matrix.pixi-environment }} test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          manifest-path: pyproject.toml
      - name: Run tests
        run: pixi run test
      - name: Publish code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
