name: PyPI Publish

on:
  push:
    tags: ['*']

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: publish

    permissions:
        id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
